[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  headers = { Cache-Control = "public, max-age=0, must-revalidate" }

[[redirects]]
  from = "/site.webmanifest"
  to = "/site.webmanifest"
  status = 200
  headers = { Content-Type = "application/manifest+json" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


